sudo: required
language: cpp

compiler:  
    - gcc

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
  - sudo apt-get update -q
  - sudo apt-get update -qq
  - sudo apt-get install cmake


install:
- sudo apt-get install cmake
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++" CC="clang"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang

before_script:  
    - git clone https://github.com/onqtam/doctest.git
    - mkdir build
    - cd build
    - cmake ..

script: 
    - make
    - make test  
